### ISSUE TITLE
Specify image value

### ISSUE THREAD

**Issue by karlek** [datasektionen/taitan#4]
Should image be a URL?

**Comment by karlek** [comment]
How should the image URL be saved? As a image.url file in each folder?

**Comment by Yopi** [comment]
Maybe a config file? Are image URLs the only things that need specifying for each page? I think you can decide what you think works the best, since it's only an implementation question rather than an API-question.

**Comment by karlek** [comment]
Yeah. The title could (should?) also be in the config; right now it's extracted from the first `<h1>` element.
